### ISSUE TITLE
How to build ortextensions.dll?

### ISSUE THREAD

**Issue by jdluzen** [cassiebreviu/StableDiffusion#13]
I've built the main branch of onnxruntime-extensions successfully, however the ortextensions.dll does not work and the file size is massively different. Are there special configurations needed to build it? I'll have to build it for osx-x64, linux-x64, and linux-arm64 as well.

**Comment by cassiebreviu** [comment]
Here are the build instructions for the extensions dll https://github.com/microsoft/onnxruntime-extensions/blob/main/docs/development.md
