### ISSUE TITLE
ortextensions won't load

### ISSUE THREAD

**Issue by btarg** [cassiebreviu/StableDiffusion#15]
I just cloned the DirectML version of the repo since I'm running an RX 5700, and I get this error when clicking play in Visual Studio 2022:
```Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:Fail] LoadLibrary failed with error 126 "" when trying to load "E:\StableDiffusion-direct-ML-EP\ortextensions.dll"'
```

**Comment by cassiebreviu** [comment]
The error is blank, can you add the issue?

**Comment by alanextar** [comment]
I think the error is as follows
`Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:Fail] LoadLibrary failed with error 126 "" when trying to load "ortextensions.dll"'`

**Comment by cassiebreviu** [comment]
Hey! There is a new version of onnx runtime and onnx runtime extensions that will resolve this issue. If you want to try the pre-release alpha versions they are in nuget now. Then to load the dll you simply call "sessionOptions.RegisterOrtExtensions();"
