### ISSUE TITLE
VAE is always decoded on CPU

### ISSUE THREAD

**Issue by Trojaner** [cassiebreviu/StableDiffusion#17]
I believe the issue is caused [by this line in VaeDecoder.Decode](https://github.com/cassiebreviu/StableDiffusion/blob/main/StableDiffusion.ML.OnnxRuntime/VaeDecoder.cs#L13) because no sessionOptions are passed to InferenceSession.

I added `SessionOptions.MakeSessionOptionWithCudaProvider()` and it started using the GPU instead.

**Comment by MahdiFarasat** [comment]
where?
