### ISSUE TITLE
load failed ortextensions.dll 

### ISSUE THREAD

**Issue by AJ-comp** [cassiebreviu/StableDiffusion#18]
I have clone this project and edit configure content as below. (update the dll file path and onnx file path)
I haven't changed anything other than that in the source.
![image](https://user-images.githubusercontent.com/69152847/235307559-7d9c96fa-c52b-4ee4-b2f2-f6989dd3a67d.png)

And I did copy and paste the onnx file and the dll file to the execution file path.
The result is as below.
![image](https://user-images.githubusercontent.com/69152847/235307681-88de6df2-b7eb-463f-9b30-4b9bf33deeb9.png)

And I execute the source file in the debug mode and I faced an error as below.
![image](https://user-images.githubusercontent.com/69152847/235307282-c1e63d03-dbcc-4e40-8f7c-3df03cbc2761.png)

There is a ortextensions.dll file in the path as below
![image](https://user-images.githubusercontent.com/69152847/235307350-7436ddbb-d99c-4020-8076-b32aa0a1a9d8.png)

Could you tell me the solution?

**Comment by alanextar** [comment]
Have the same issue

**Comment by cassiebreviu** [comment]
Hey! There is a new version of onnx runtime and onnx runtime extensions that will resolve this issue. If you want to try the pre-release alpha versions they are in nuget now. Then to load the dll you simply call "sessionOptions.RegisterOrtExtensions();"
