### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by adoconnection** [cassiebreviu/StableDiffusion#2]
First of all I appriciate your effort.

But. This kind of approach always amaze me till deepest levels: to share a code to entire NET community that is simply not working from the very beginning. Have you tried to run this code at least once? 

```safety_checker``` and ```unet``` folders and models are missing. 

```
Directory.GetCurrentDirectory().ToString() + ("\\text_tokenizer\\custom_op_cliptok.onnx"
```
with all the respect, its like you are using c# for the second time in your life, but alreay writing NET blog posts 🙈

**Comment by TheBlubb14** [comment]
I think you missed to read the readme

https://github.com/cassiebreviu/StableDiffusion/blob/main/README.md#use-hugging-face-to-download-the-stable-diffusion-models

> - Copy the folders with the ONNX files to the C# project folder `\StableDiffusion\StableDiffusion`. The folders to copy are: `unet`, `vae_decoder`, `text_encoder`, `safety_checker`.
