### ISSUE TITLE
Diffusers porting and Avalonia demo app

### ISSUE THREAD

**Issue by gianni-rg** [cassiebreviu/StableDiffusion#20]
Hello, I'd like to share with you about a side-project I'm working on, started few months ago, and I'm using to present Generative AI topics in community events: it's an experimental porting of Diffusers in .NET ([SharpDiffusion](https://github.com/gianni-rg/SharpDiffusion)), and a basic [demo application built with Avalonia](https://github.com/gianni-rg/gen-ai-net-playground), supporting both original SD 1.x ONNX models, as well as FP16 optimized models. I was about to implement the port of the CLIPTokenizer, then I found this repo and leveraged some code for it, thanks to the ONNX Extensions. Thank you for sharing! It would be interesting to have a discussion about possible collaborations and/or future developments.

**Comment by axodox** [comment]
Cool, I am doing the same, but with C++ here: https://github.com/axodox/axodox-machinelearning
This is my sample app: https://github.com/axodox/unpaint
