### ISSUE TITLE
DirectML doesn't use gpu

### ISSUE THREAD

**Issue by Deins** [cassiebreviu/StableDiffusion#28]
Currently I don't see how DirectML is supposed to work with gpu. `device_id` in `sessionOptions.AppendExecutionProvider_DML`as I understand is supposed to be DirectML device created with https://learn.microsoft.com/en-us/windows/win32/api/directml/nf-directml-dmlcreatedevice
While I can't seem to find any c# exposed functions to actually create such device.

What id is supposed to be used `AppendExecutionProvider_DML` ?

**Comment by cassiebreviu** [comment]
Did you check to make sure the Device ID is correct in the config? It depends on your device. Usually `DeviceId=0` is correct, however if you are on a laptop with an integrated GPU and external, you might need `DeviceId=1`
