### ISSUE TITLE
LoadLibrary failed with error 126 when trying to load "ortextensions.dll"

### ISSUE THREAD

**Issue by ibebbs** [cassiebreviu/StableDiffusion#3]
Hi,

Really want to try out this project. Unfortunately it throws a `OnnxRuntime.OnnxRuntimeException: [ErrorCode:Fail] LoadLibrary failed with error 126 "" when trying to load "ortextensions.dll"` exception whenever I run this app (using `dotnet run` or through Visual Studio).

I have tried installing numerous versions of CUDA and CUDNN (version 12.1,  11.6.2 & 11.4.4 with associated CUDNN versions) by following the linked guide and while each seems to install correctly, I still encounter this error.

Could you provide some info on the exact version required by this project or what else may be causing the exception above?

Many thanks in advance...

**Comment by cassiebreviu** [comment]
I pushed a fix. If you get latest it should solve your issue. Thanks!
