### ISSUE TITLE
Numeric instability in LMS

### ISSUE THREAD

**Issue by jlami** [cassiebreviu/StableDiffusion#5]
Hi,

When I try to run with other `num_inference_steps`, for instance 30, I get very grainy results.

I am trying to compare the numbers that python is using and a lot of the calculations in C# are not lining up with it. Seems that numpy and torch use doubles internally for computations and only store floats in the resulting arrays. This might have some influence, but I have not tracked it down.

I am running this in dotnet 4.8, but I don't think that makes any difference.

A prompt of `portrait photo of a old warrior chief` with a seed of 0 gives me the following image:

![sample](https://user-images.githubusercontent.com/8522993/225354295-65daea8f-247f-4f4a-b23b-6f73f3a46599.png)

I don't know enough about schedulers to know if using another algorithm might fix this. Or if there is an easy way to test if the LMS will converge.

Maybe you can try higher inference steps and see if this is reproducible?

**Comment by cassiebreviu** [comment]
I played around with this and I think it comes down to working with the prompt, steps and seed to get the result you want. When I built the scheduler I performed tests and validated the same output and input in python and C# for each function formula in the scheduler to validate I had implemented the logic correctly and to debug issues when trying to get it to work. 

I tested this prompt with a bigger random seed and 10 steps and get a very high res photo. Can you try changing your prompt to an "hd portrait photo of a old warrior chief" and see how the result changes? Play with the seed and steps to get the result you want.

See my testing below:
Example: 10 Steps, random large seed, prompt "portrait photo of a old warrior chief"
![sample-10-steps-randomseed](https://user-images.githubusercontent.com/46505951/225372892-1b952fe4-6712-4213-bb05-bf62beb68200.png)

Example: 29 Steps, Seed 0, prompt "portrait photo of a old warrior chief"
![sample-29-steps-old-seed0](https://user-images.githubusercontent.com/46505951/225370943-5ff46e53-ff4a-4d34-9e28-8769b40d7f8e.png)

Example: 29 Steps, Seed 0, prompt "hd portrait photo of a old warrior chief"
![sample-29steps-hd-seed0](https://user-images.githubusercontent.com/46505951/225371318-601c0012-775a-42a0-b682-3ed9d360369b.png)

I think old can also mean an old photo and therefore lower resolution. 

Hope this helps! Thanks!

**Comment by jlami** [comment]
I think I found it, you store the derivative reversed here: 

https://github.com/cassiebreviu/StableDiffusion/blob/fabfe663d68badc545f1635f39c450074b2998e5/StableDiffusion/LMSDiscreteScheduler.cs#L227-L230

You should only give the zip the reversed and store the normal one. I'll make a pull request with the fix

This is the image I get with the fix:

![sample](https://user-images.githubusercontent.com/8522993/225402430-4cb01605-1d61-4e26-a684-198cc5443e0b.png)
